name: hack-2025
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - liblzma=5.8.1=hd471939_2
  - libsqlite=3.51.0=h86bffb9_0
  - libzlib=1.3.1=hd23fc13_2
  - ncurses=6.5=h0622a9a_3
  - openssl=3.5.4=h230baf5_0
  - pip=25.2=pyh8b19718_0
  - python=3.12.12=h74c2667_1_cpython
  - readline=8.2=h7cca4af_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=hf689a15_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.72.0
      - anyio==4.11.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.10.2
      - numpy==2.3.4
      - openai==2.7.1
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.28.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - streamlit==1.51.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
